print("Lear python")
print("Hello world")
print("2023")
print(2023)
print("My age is 27")
print(True)
print(False)
print("Hello " + str(2023))
print("This file type is \"Python file\"")
print("============================================")
print(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)